### PR TITLE
New sounds added

### PR DESCRIPTION
**Pull request by Lena0020**
Sounds for player/enemy and background music
https://s24109.atlassian.net/browse/SCRUM-94

### CODE REVIEW

**Comment by FrozzLab** [comment]
I really like the selection, approval from me :>

**Comment by WildCup** [comment]
please use 'feature' prefix for you branch as explained in the wiki. This is global-wide convention for git regardless of project type or language. It is not just for aesthetics, it is used in pipelines or other application. Like if you want to have automatics builds for you application you'd determine on branch name what should happen like: 
dev -> release to dev enviroment,
main -> release to production
feature/* -> build and test without release,
etc.

Or you could use branch name to determine version like 
main -> stable
dev -> beta 
feature/* -> alpha

there are other application that based on branch name would categorize your branches, for easier management, like the one I'm using  git-graph
image

it collors branches 
main -> blue
dev -> yellow
feature/* -> light blue 
bug -> red

it all because naming branches this way is a convention that we should follow

**Comment by WildCup** [comment]
I think player-hiding doesn't fit to our game or platformer in general but more to 1st person survival like the forest. Maybe leaves effect would be fine when we enter and leave a hideout? Deepens how we design hideouts. What the rest thinks?

**Comment by WildCup** [comment]
I reeeeeeally like player-death-1 but I'd delete player-death-2 right away :D 1st one fits very well to our dark theme meritorious story. I'm not sure with enemies deaths but I think we can test that in practice.

**Comment by WildCup** [comment]
please rename 'background-music-2 (2)' to 'background-music-2'. Please delete 'test' sounds lvl1-tmp and player-jump-tmp and assign all the sounds and musics in Audio manager prefab with appropriate name (ping me if you don't know what I mean). I think it belongs to this PR

**Review by WildCup — CHANGES_REQUESTED** [review]
overall good job!! I can't wait to hear it in action

**Pull request closed without merging**
